services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.development
    container_name: django-app
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:16
    container_name: postgres-db
    volumes:
      - postgres-db:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER} -d ${PGDATABASE}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
volumes:
  postgres-db: